### PR TITLE
fix and improve delete flushing

### LINKED ISSUE #86: Crash writeWithFSync on a null block
I am not sure exactly what triggered this crash but I'll document it as well as I can.

I'm running AAOL 4.3.5 and jitdb 7.0.1 and ssb-db2 4.2.1 in Manyverse. Some 30s after app startup (and all other queries working as normally), in the middle of making several ssb-db2 `deleteFeed` calls (no compaction yet), I got this crash for the ~20th `deleteFeed` call:

Screenshot from 2022-08-03 11-46-12

The lines of code are in random-access-storage v1.4.3:

https://github.com/random-access-storage/random-access-storage/blob/50dd02fd07d5d1690a3346684f8aac74dd76d017/index.js#L65

and

https://github.com/ssbc/async-append-only-log/blob/24e6d487a058cd3b27c74eab3d478428f13a8745/index.js#L162

which can only mean we tried to write a blockBuf that was `null` not a Buffer. Seems very strange that we would end up with a null blockBuf.

### PR DESCRIPTION
**Pull request by staltz**
I'm gonna take a wild guess and assume that this PR fixes #86.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -311,12 +312,12 @@ module.exports = function AsyncAppendOnlyLog(filename, opts) {
     const blockStart = blockIndex * blockSize
     const blockBuf = blocksWithDeletables.get(blockIndex)
     blocksWithDeletables.delete(blockIndex)
-    blocksWithDeletables.set(-1, null) // indicate that flush is active
+    flushingDelete = true
```
Comment (staltz) [inline index.js:315]: This `set(-1, null)` trick seemed smart at the time, but this `null` blockBuf may be causing #87, and booleans are so cheap, we shouldn't be afraid to have one here.

Comment (arj03) [reply index.js:315]: right, seems problematic that we can't count on size with that trick.

**Review by arj03 — APPROVED** [review]
👍 overall less complicated and this seems likely that it could be a problem
